# This is a basic workflow to help you get started with Actions

name: MakeGame

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      production:
        description: 'Deploy to production (default: false). If false, will deploy to test subfolder.'
        required: false
        default: false
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Update packages
        run: sudo apt install -y unzip make nodejs gettext build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl
 
      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- -v -y
          sudo ln -s $HOME/.elan/bin/* /usr/local/bin;

      - name: Install python Lean dependencies
        run: |
          python -m pip install --upgrade pip requests markdown2 toml mathlibtools toposort invoke

      - name: upgrade Lean and dependencies
        uses: leanprover-contrib/lean-upgrade-action@master
        with:
          repo: ${{ github.repository }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Game maker
        run: |
          git clone https://github.com/mmasdeu/Lean-game-maker.git
          cd Lean-game-maker/src/interactive_interface
          npm install .
          ./node_modules/.bin/webpack --mode=production
          cd ../..
          pip3 install -e .

      - name : Get server files
        run: |
          curl -s https://api.github.com/repos/leanprover-community/lean/releases/latest | grep "browser.zip" | grep -v name | cut -d : -f 2,3 | tr -d \"  | wget -qi -
          unzip *.zip
          VER=`ls *zip | cut -c 6-11`
          mkdir -p "Lean-game-maker/src/interactive_interface/lean_server/leanprover-community/lean:$VER/"
          cp build/shell/* "Lean-game-maker/src/interactive_interface/lean_server/leanprover-community/lean:$VER/"
          
      - name: Make game
        run: make-lean-game

      - name: Deploy Production
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: ${{ github.event.inputs.production }}
        with:
          token: ${{ secrets.github_token }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./html # The folder the action should deploy.
          single-commit: "true"

      - name: Deploy Test
        uses: JamesIves/github-pages-deploy-action@4.1.5
        if: ${{ !github.event.inputs.production }}
        with:
          token: ${{ secrets.github_token }}
          branch: gh-pages # The branch the action should deploy to.
          folder: ./html # The folder the action should deploy.
          target-folder: test/
          single-commit: "false"

